// <auto-generated />
using System;
using ExpenseTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    partial class ExpenseTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("ExpenseTracker.Domain.Expenses.ExpenseCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("ExpenseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "housing",
                            ColorToken = "rose",
                            DisplayOrder = 1,
                            Name = "Housing"
                        },
                        new
                        {
                            Code = "food",
                            ColorToken = "amber",
                            DisplayOrder = 2,
                            Name = "Food"
                        },
                        new
                        {
                            Code = "transport",
                            ColorToken = "sky",
                            DisplayOrder = 3,
                            Name = "Transport"
                        },
                        new
                        {
                            Code = "utilities",
                            ColorToken = "emerald",
                            DisplayOrder = 4,
                            Name = "Utilities"
                        },
                        new
                        {
                            Code = "health",
                            ColorToken = "violet",
                            DisplayOrder = 5,
                            Name = "Health"
                        },
                        new
                        {
                            Code = "shopping",
                            ColorToken = "fuchsia",
                            DisplayOrder = 6,
                            Name = "Shopping"
                        },
                        new
                        {
                            Code = "entertainment",
                            ColorToken = "orange",
                            DisplayOrder = 7,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Code = "other",
                            ColorToken = "slate",
                            DisplayOrder = 8,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Expenses.ExpenseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("MonthKey");

                    b.ToTable("ExpenseEntries", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Expenses.ExpenseEntry", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Expenses.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
